version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  test_backend:
    executor: node-executor
    working_directory: ~/project/backend
    steps:
      - checkout:
          path: ~/project
      - run: npm install
      - run: npm test

  test_frontend:
    executor: node-executor
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: frontend-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: frontend-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test

  cypress_test:
    executor: node-executor
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: frontend-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: frontend-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Start backend server
          command: npm run start
          working_directory: ~/project/backend
          background: true
      - run:
          name: Start frontend server
          command: npm run start
          working_directory: ~/project/frontend
          background: true
      - run:
          name: Wait for servers to be ready
          command: sleep 10
      - run: npx cypress run

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_backend
      - test_frontend
      - cypress_test
