version: 2.1

orbs:
  node: circleci/node@4.1.0
  postgres: onehq/postgres@1.1.0

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  install_backend_dependencies:
    executor:
      name: node-executor
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "backend/package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install Backend Dependencies
          command: cd backend && npm ci
      - save_cache:
          paths:
            - backend/node_modules
          key: v1-dependencies-{{ checksum "backend/package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - backend

  test_backend:
    docker:
      - image: circleci/node:14
        environment:
          DB_USERNAME: my_username
          DB_PASSWORD: my_password
          DB_DATABASE: my_database
          DB_HOST: localhost
          DB_DIALECT: postgres
      - image: circleci/postgres:13
        environment:
          POSTGRES_USER: my_username
          POSTGRES_PASSWORD: my_password
          POSTGRES_DB: my_database
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install PostgreSQL Client
          command: sudo apt-get update && sudo apt-get install -y postgresql-client
      - run:
          name: Wait for PostgreSQL to start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Create DB role and DB
          command: |
            psql -h localhost -U my_username -c "CREATE ROLE $DB_USERNAME WITH LOGIN CREATEDB PASSWORD '$DB_PASSWORD';"
            psql -h localhost -U my_username -c "CREATE DATABASE $DB_DATABASE WITH OWNER $DB_USERNAME;"
      - run:
          name: Run Backend
          command: cd backend && npm run start
          background: true
      - run:
          name: Install Cypress Dependencies
          command: sudo apt-get install -y libgtk-3-0 libgbm1 libasound2
      - run:
          name: Run Cypress Tests
          command: cd backend && npx cypress run

  test_frontend:
    executor: node-executor
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: frontend-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: frontend-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test

  cypress_test:
    executor: node-executor
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - restore_cache:
          key: frontend-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: frontend-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Install backend dependencies
          command: npm install
          working_directory: ~/project/backend
      - run:
          name: Start backend server
          command: npm run start
          working_directory: ~/project/backend
          background: true
      - run:
          name: Install Cypress dependencies
          command: sudo apt-get update && sudo apt-get install -y libnss3 libatk-bridge2.0-0
      - run: npx cypress run

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_backend_dependencies
      - test_backend:
          requires:
            - install_backend_dependencies
      - test_frontend
      - cypress_test
