version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  test_backend:
    docker:
      - image: circleci/node:14
      - image: circleci/postgres:13
        environment:
          POSTGRES_USER: $DB_USERNAME
          POSTGRES_DB: $DB_DATABASE
          POSTGRES_PASSWORD: $DB_PASSWORD
    working_directory: ~/project/backend
    steps:
      - checkout:
          path: ~/project
      - run: npm install
      - run:
          name: Create DB role and DB
          command: |
            psql -h 127.0.0.1 -U postgres -c "CREATE ROLE $DB_USERNAME WITH LOGIN CREATEDB PASSWORD '$DB_PASSWORD';"
            psql -h 127.0.0.1 -U postgres -c "CREATE DATABASE $DB_DATABASE WITH OWNER $DB_USERNAME;"
      - run:
          name: Run migrations
          command: npx dotenv -e test.env sequelize db:migrate
      - run:
          name: Seed data
          command: npx dotenv -e test.env sequelize db:seed:all
      - run: npm test

  test_frontend:
    executor: node-executor
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: frontend-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: frontend-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test

  cypress_test:
    executor: node-executor
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: frontend-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: frontend-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Install backend dependencies
          command: npm install
          working_directory: ~/project/backend
      - run:
          name: Start backend server
          command: npm run start
          working_directory: ~/project/backend
          background: true
      - run:
          name: Install Cypress dependencies
          command: sudo apt-get update && sudo apt-get install -y libnss3 libatk-bridge2.0-0
      - run: npx cypress run

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_backend
      - test_frontend
      - cypress_test
