version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: circleci/node:14
      - image: circleci/postgres:13
        environment:
          POSTGRES_USER: $DB_USERNAME
          POSTGRES_DB: $DB_DATABASE
          POSTGRES_PASSWORD: $DB_PASSWORD
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install additional dependencies
          command: sudo apt-get update && sudo apt-get install -y libnss3
      - run:
          name: Install per-env
          command: npm install per-env
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Run Cypress
          command: npx cypress run

  test_backend:
    docker:
      - image: circleci/node:14
    working_directory: ~/project/backend
    steps:
      - checkout:
          path: ~/project
      - run: npm install
      - run: npm test

  test_frontend:
    docker:
      - image: circleci/node:14
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: frontend-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: frontend-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test

  cypress_test:
    docker:
      - image: circleci/node:14
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: frontend-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: frontend-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Start backend server
          command: npm run start
          working_directory: ~/project/backend
          background: true
      - run:
          name: Start frontend server
          command: npm run start
          working_directory: ~/project/frontend
          background: true
      - run:
          name: Wait for servers to be ready
          command: sleep 10
      - run: npx cypress run

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_backend
      - test_frontend
      - cypress_test
