name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Install backend dependencies
      working-directory: backend
      run: npm install

    - name: Run migrations
      working-directory: backend
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: npx sequelize-cli db:migrate

    - name: Run seeders
      working-directory: backend
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: npx sequelize-cli db:seed:all

    - name: Run backend tests
      working-directory: backend
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: npm test
